### ISSUE TITLE
Missing Leprechaun for Code Generation

### ISSUE THREAD

**Issue by GuitarRich** [klpatil/sc-learning-mind-map#1]
I'd probably remove T4 for code gen as that is now really old and rarely works well. https://github.com/blipson89/Leprechaun is currently the best option for any code-gen you want to do in your Sitecore instance.

**Comment by klpatil** [comment]
Thank you @GuitarRich for the suggestion. Mind map updated: https://www.mindomo.com/mindmap/4e574017784f416fbaa6775671d19cf8
