### ISSUE TITLE
Adding a Sitecore Browser extensions section

### ISSUE THREAD

**Issue by ugo-quaisse** [klpatil/sc-learning-mind-map#2]
I think it would be useful to list existing Sitecore Browser extensions like:

Sitecore Author Toolbox:
https://chrome.google.com/webstore/detail/sitecore-author-toolbox/mckfcmcdbgkgffdknpkaihjigmcnnbco?hl=en

Sitecore Extensions:
https://chrome.google.com/webstore/detail/sitecore-extensions/aoclhcccfdkjddgpaaajldgljhllhgmd?hl=en

Sitecore Developer tools:
https://chrome.google.com/webstore/detail/sitecore-developer-tool/cmbppbejihcnbngefandoljljdppnlda?hl=en

Thanks
Ugo

**Comment by klpatil** [comment]
Thanks, @ugo-quaisse - Added new topic "Browser extensions": https://www.mindomo.com/mindmap/sitecore-learning-mind-map-4e574017784f416fbaa6775671d19cf8
