### ISSUE TITLE
Good to include Useful Modules

### ISSUE THREAD

**Issue by AmitKumar-AK** [klpatil/sc-learning-mind-map#3]
It will be good to include :
- Advance Image module which uses image field with focus cropping option. Allows content authors to set focal point on images and cropping is done based on defined axes.
URL: https://github.com/AmitKumar-AK/sitecore-fields

- SITECORE LOG ANALYZER (SCLA) https://marketplace.sitecore.net/en/Modules/Sitecore_Log_Analyzer.aspx, and it's working with Sitecore 10.0
- Content Export Tool: https://github.com/estockwell-alpert/ContentExportTool
- Steps to use Visual Studio Code Extension to watch Sitecore Logs:  https://blog.alexvanwolferen.nl/using-100-percent-free-tools-to-watch-your-sitecore-logging-using-visual-studio-code-and-a-single-extension/
- Sitecore Url Mapper for Siteore/Sitecore JSS Sites: https://github.com/unic/SitecoreUrlMapper2

**Comment by klpatil** [comment]
Thanks, Amit - Done!
https://www.mindomo.com/mindmap/4e574017784f416fbaa6775671d19cf8

**Comment by AmitKumar-AK** [comment]
Thanks for including the details

BR,
Amit Kumar
Sent from Mobile. Please ignore typos & brevity.
________________________________
