### ISSUE TITLE
Adding some additional points

### ISSUE THREAD

**Issue by sreekrishnan1993** [klpatil/sc-learning-mind-map#4]
In Sitecore Learning section : suggest adding
1. Sitecore Elearning : https://learning.sitecore.com/
2. Sitecore Telegram - https://t.me/SitecoreTelegram

In Search section : suggest adding
1. Coveo

In Sitecore Events - Community Managed : suggest adding
1. Sitecore User Groups : https://www.reddit.com/r/sitecore/wiki/user-groups

**Comment by klpatil** [comment]
Thanks, @sreekrishnan1993  - Done!
